stow -t ~/ alacritty
stow -t ~/ bash
stow -t ~/ foot
stow -t ~/ gammastep
stow -t ~/ gtk-3.0
stow -t ~/ lf
stow -t ~/ luakit
stow -t ~/ mako
stow -t ~/ mpd
stow -t ~/ mpDris2
stow -t ~/ mpv
stow -t ~/ ncmpcpp
stow -t ~/ nvim
stow -t ~/ qt5ct
stow -t ~/ river
stow -t ~/ scripts
stow -t ~/ sv
stow -t ~/ sway
stow -t ~/ tmux
stow -t ~/ waybar
stow -t ~/ wofi
stow -t ~/ xonsh
stow -t ~/ zathura
stow -t ~/ zsh
stow -t ~/ zzz
