permit persist keepenv :wheel
permit nopass keepenv :wheel
permit nopass antonio cmd reboot
permit nopass antonio cmd poweroff
permit nopass antonio cmd xbps-install
permit nopass antonio cmd tor-restart
permit nopass antonio cmd sv
permit nopass antonio cmd tee_turbo
permit nopass antonio cmd swaylock
permit nopass root cmd swaylock
permit nopass keepenv root
