# Window rules ########
windowrule = float, ^(mpv)$
windowrule = pin, ^(mpv)$
windowrule = float, ^(pavucontrol-qt)$
windowrule = float, ^(float)$
windowrule = float, ^(blueman-manager)$
windowrule = float, title:^(synomail_ui.py)$

windowrule = move cursor 20 -50%, ^(waybar)$

# Dialogs
windowrule=float,title:^(iwgtk)$
windowrule=float,title:^(Open File)(.*)$
windowrule=float,title:^(Open Folder)(.*)$
windowrule=float,title:^(Save As)(.*)$
windowrule=float,title:^(Library)(.*)$ 

windowrulev2 = rounding 10, floating:1

# Layer rules ########
#layerrule = blur, gtk-layer-shell
#layerrule = ignorezero, gtk-layer-shell
#layerrule = blur, waybar
#layerrule = ignorezero, waybar
