[FileDialog]
history=file:///home/antonio, file:///home/antonio/Downloads, file:///home/antonio/Downloads/registration, file:///home/antonio/Downloads/registration/visa, file:///home/antonio/Downloads/documentos
lastVisited=file:///home/antonio/Downloads
qtVersion=6.8.2
shortcuts=file:, file:///home/antonio
sidebarWidth=115
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3\x4\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\xbc\0\0\0\x1\0\0\0\0\0\0\0W\0\0\0\x1\0\0\0\0\0\0\0W\0\0\0\x1\0\0\0\0\0\0\0\x9a\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)
viewMode=Detail
