#!/bin/sh
test -f /run/user/1000/wayland-1.lock >/dev/null || exit 1

lat=$(head -n 1 filename)
lon=$(head -n 2 filename)

exec wlsunset -l $lat -L $lon -g 0.8 -t 3800 -T 6200

# Delhi
#exec wlsunset -l 28.4 -L 77.1 -g 0.8 -t 3500 -T 5700

# Mumbai
#exec wlsunset -l 19.1 -L 72.9 -g 0.8 -t 3500 -T 5700
